using System;
using System.Collections.Generic;

namespace WebApplication1.Models.BalimoonBML
{
    public partial class Customers
    {
        public int CustomerId { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerName2 { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerCity { get; set; }
        public string CustomerContact { get; set; }
        public string CustomerPhoneNo { get; set; }
        public string CustomerFaxNo { get; set; }
        public string CustomerMobileNo { get; set; }
        public string OurAccountNo { get; set; }
        public string GlobalDimension1Code { get; set; }
        public string GlobalDimension2Code { get; set; }
        public string ChainName { get; set; }
        public decimal? BudgetedAmount { get; set; }
        public decimal? CreditLimitLcy { get; set; }
        public string CustomerPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public string CustomerPriceGroup { get; set; }
        public string LanguageCode { get; set; }
        public int? StatisticsGroup { get; set; }
        public string PaymentTermsCode { get; set; }
        public string FinChargeTermsCode { get; set; }
        public string SalespersonCode { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string ShippingAgentCode { get; set; }
        public string PlaceofExport { get; set; }
        public string InvoiceDiscCode { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string CustomerCountry { get; set; }
        public string CollectionMethod { get; set; }
        public decimal? Amount { get; set; }
        public int? InvoiceCopies { get; set; }
        public int? LastStatementNo { get; set; }
        public byte? PrintStatements { get; set; }
        public string BilltoCustomerNo { get; set; }
        public int? Priority { get; set; }
        public string PaymentMethodCode { get; set; }
        public int? ApplicationMethod { get; set; }
        public byte? PricesIncludingVat { get; set; }
        public string LocationCode { get; set; }
        public string TelexAnswerBack { get; set; }
        public string VatregistrationNo { get; set; }
        public byte? CombineShipments { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string FilePicture { get; set; }
        public string CustomerPostCode { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerHomePage { get; set; }
        public string ReminderTermsCode { get; set; }
        public string NoSeries { get; set; }
        public string TaxAreaCode { get; set; }
        public byte? TaxLiable { get; set; }
        public string VatbusPostingGroup { get; set; }
        public int? Reserve { get; set; }
        public byte? BlockPaymentTolerance { get; set; }
        public string IcpartnerCode { get; set; }
        public decimal? PrepaymentPercent { get; set; }
        public string PrimaryContactNo { get; set; }
        public string ResponsibilityCenter { get; set; }
        public int? ShippingAdvice { get; set; }
        public string ShippingTime { get; set; }
        public string ShippingAgentServiceCode { get; set; }
        public string ServiceZoneCode { get; set; }
        public byte? AllowLineDisc { get; set; }
        public string BaseCalendarCode { get; set; }
        public int? CopySelltoAddrtoQteFrom { get; set; }
        public string Abn { get; set; }
        public byte? Registered { get; set; }
        public string AbndivisionPartNo { get; set; }
        public string Irdno { get; set; }
        public int? Sttype { get; set; }
        public DateTime? StexpiryDate { get; set; }
        public int? ComponentsonSalesOrders { get; set; }
        public int? ComponentsonShipments { get; set; }
        public int? ComponentsonInvoices { get; set; }
        public int? TaxDocumentType { get; set; }
        public int? Blocked { get; set; }
        public string Segment { get; set; }
        public string SubSegment { get; set; }
        public string Region { get; set; }
        public string SubRegion { get; set; }
        public string Npwpno { get; set; }
        public string Npwpname { get; set; }
        public string Npwpname1 { get; set; }
        public string Npwpaddress { get; set; }
        public string Npwpaddress1 { get; set; }
        public DateTime? Tglpengukuhan { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
        public string DimensionValue01Code { get; set; }
        public string DimensionValue02Code { get; set; }
        public string DimensionValue03Code { get; set; }
        public string DimensionValue04Code { get; set; }
        public string DimensionValue05Code { get; set; }
    }
}
