using System;
using System.Collections.Generic;

namespace WebApplication1.Models.BalimoonBML
{
    public partial class GenJournalLine
    {
        public int GenJournalLineId { get; set; }
        public int GenJournalHeaderId { get; set; }
        public string JournalTemplateName { get; set; }
        public string JournalBatchName { get; set; }
        public string DocumentNo { get; set; }
        public int SeqLineNo { get; set; }
        public string JournalDescription { get; set; }
        public int? AccountType { get; set; }
        public string AccountNo { get; set; }
        public DateTime? PostingDate { get; set; }
        public int? DocumentType { get; set; }
        public string Description { get; set; }
        public decimal? Vatpercent { get; set; }
        public string BalAccountNo { get; set; }
        public string CurrencyCode { get; set; }
        public decimal? DebitAmount { get; set; }
        public decimal? CreditAmount { get; set; }
        public decimal? AmountLcy { get; set; }
        public decimal? BalanceLcy { get; set; }
        public decimal? CurrencyFactor { get; set; }
        public decimal? SalesPurchLcy { get; set; }
        public decimal? ProfitLcy { get; set; }
        public decimal? InvDiscountLcy { get; set; }
        public string BilltoPaytoNo { get; set; }
        public string PostingGroup { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string SalespersPurchCode { get; set; }
        public string SourceCode { get; set; }
        public byte? SystemCreatedEntry { get; set; }
        public string OnHold { get; set; }
        public int? AppliestoDocType { get; set; }
        public string AppliestoDocNo { get; set; }
        public DateTime? DueDate { get; set; }
        public DateTime? PmtDiscountDate { get; set; }
        public decimal? PaymentDiscountPercent { get; set; }
        public string JobNo { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Vatamount { get; set; }
        public int? Vatposting { get; set; }
        public string PaymentTermsCode { get; set; }
        public string AppliestoId { get; set; }
        public string BusinessUnitCode { get; set; }
        public string ReasonCode { get; set; }
        public int? RecurringMethod { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string RecurringFrequency { get; set; }
        public int? GenPostingType { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public int? VatcalculationType { get; set; }
        public byte? Eu3partyTrade { get; set; }
        public byte? AllowApplication { get; set; }
        public int? BalAccountType { get; set; }
        public int? BalGenPostingType { get; set; }
        public string BalGenBusPostingGroup { get; set; }
        public string BalGenProdPostingGroup { get; set; }
        public int? BalVatcalculationType { get; set; }
        public decimal? BalVatpercent { get; set; }
        public decimal? BalVatamount { get; set; }
        public int? BankPaymentType { get; set; }
        public decimal? VatbaseAmount { get; set; }
        public decimal? BalVatbaseAmount { get; set; }
        public byte? Correction { get; set; }
        public byte? CheckPrinted { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public int? SourceType { get; set; }
        public string SourceNo { get; set; }
        public string PostingNoSeries { get; set; }
        public string TaxAreaCode { get; set; }
        public byte? TaxLiable { get; set; }
        public string TaxGroupCode { get; set; }
        public byte? UseTax { get; set; }
        public string BalTaxAreaCode { get; set; }
        public byte? BalTaxLiable { get; set; }
        public string BalTaxGroupCode { get; set; }
        public byte? BalUseTax { get; set; }
        public string VatbusPostingGroup { get; set; }
        public string VatprodPostingGroup { get; set; }
        public string BalVatbusPostingGroup { get; set; }
        public string BalVatprodPostingGroup { get; set; }
        public int? AdditionalCurrencyPosting { get; set; }
        public decimal? FaaddCurrencyFactor { get; set; }
        public string SourceCurrencyCode { get; set; }
        public decimal? SourceCurrencyAmount { get; set; }
        public decimal? SourceCurrVatbaseAmount { get; set; }
        public decimal? SourceCurrVatamount { get; set; }
        public decimal? VatbaseDiscountPercent { get; set; }
        public decimal? VatamountLcy { get; set; }
        public decimal? VatbaseAmountLcy { get; set; }
        public decimal? BalVatamountLcy { get; set; }
        public decimal? BalVatbaseAmountLcy { get; set; }
        public byte? ReversingEntry { get; set; }
        public byte? AllowZeroAmountPosting { get; set; }
        public string ShiptoOrderAddressCode { get; set; }
        public decimal? Vatdifference { get; set; }
        public decimal? BalVatdifference { get; set; }
        public string IcpartnerCode { get; set; }
        public int? Icdirection { get; set; }
        public string IcpartnerGlaccNo { get; set; }
        public int? IcpartnerTransactionNo { get; set; }
        public string SelltoBuyfromNo { get; set; }
        public string VatregistrationNo { get; set; }
        public string Country { get; set; }
        public byte? Prepayment { get; set; }
        public byte? FinancialVoid { get; set; }
        public string CreditCardNo { get; set; }
        public string JobTaskNo { get; set; }
        public decimal? JobUnitPriceLcy { get; set; }
        public decimal? JobTotalPriceLcy { get; set; }
        public decimal? JobQuantity { get; set; }
        public decimal? JobUnitCostLcy { get; set; }
        public decimal? JobLineDiscountPercent { get; set; }
        public decimal? JobLineDiscAmountLcy { get; set; }
        public string JobUnitOfMeasureCode { get; set; }
        public int? JobLineType { get; set; }
        public decimal? JobUnitPrice { get; set; }
        public decimal? JobTotalPrice { get; set; }
        public decimal? JobUnitCost { get; set; }
        public decimal? JobTotalCost { get; set; }
        public decimal? JobLineDiscountAmount { get; set; }
        public decimal? JobLineAmount { get; set; }
        public decimal? JobTotalCostLcy { get; set; }
        public decimal? JobLineAmountLcy { get; set; }
        public decimal? JobCurrencyFactor { get; set; }
        public string JobCurrencyCode { get; set; }
        public string CampaignNo { get; set; }
        public string ProdOrderNo { get; set; }
        public DateTime? FapostingDate { get; set; }
        public int? FapostingType { get; set; }
        public string DepreciationBookCode { get; set; }
        public decimal? SalvageValue { get; set; }
        public int? NoofDepreciationDays { get; set; }
        public byte? DepruntilFapostingDate { get; set; }
        public byte? DeprAcquisitionCost { get; set; }
        public string MaintenanceCode { get; set; }
        public string InsuranceNo { get; set; }
        public string BudgetedFano { get; set; }
        public string DuplicateinDepreciationBook { get; set; }
        public byte? UseDuplicationList { get; set; }
        public byte? FareclassificationEntry { get; set; }
        public int? FaerrorEntryNo { get; set; }
        public byte? IndexEntry { get; set; }
        public string BatchNo { get; set; }
        public byte? OnlyTwoDimensions { get; set; }
        public byte? InStoreCreatedEntry { get; set; }
        public string StatementNo { get; set; }
        public string SelltoContactNo { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
        public decimal? Amount { get; set; }
    }
}
