using System;
using System.Collections.Generic;

namespace WebApplication1.Models.BalimoonBML
{
    public partial class Items
    {
        public int ItemId { get; set; }
        public string ItemNo { get; set; }
        public string ItemNo2 { get; set; }
        public string Description { get; set; }
        public string SearchDescription { get; set; }
        public string Description2 { get; set; }
        public string BaseUnitofMeasure { get; set; }
        public int? PriceUnitConversion { get; set; }
        public string InventoryPostingGroup { get; set; }
        public string ShelfNo { get; set; }
        public string ItemDiscGroup { get; set; }
        public byte? AllowInvoiceDisc { get; set; }
        public int? StatisticsGroup { get; set; }
        public int? CommissionGroup { get; set; }
        public decimal? UnitPrice { get; set; }
        public int? PriceProfitCalculation { get; set; }
        public decimal? ProfitPercent { get; set; }
        public int? CostingMethod { get; set; }
        public decimal? UnitCost { get; set; }
        public decimal? StandardCost { get; set; }
        public decimal? LastDirectCost { get; set; }
        public decimal? IndirectCostPercent { get; set; }
        public byte? CostisAdjusted { get; set; }
        public byte? AllowOnlineAdjustment { get; set; }
        public string VendorNo { get; set; }
        public string VendorItemNo { get; set; }
        public string LeadTimeCalculation { get; set; }
        public decimal? ReorderPoint { get; set; }
        public decimal? MaximumInventory { get; set; }
        public decimal? ReorderQuantity { get; set; }
        public string AlternativeItemNo { get; set; }
        public decimal? UnitListPrice { get; set; }
        public decimal? DutyDuePercent { get; set; }
        public string DutyCode { get; set; }
        public decimal? GrossWeight { get; set; }
        public decimal? NetWeight { get; set; }
        public decimal? UnitsperParcel { get; set; }
        public decimal? UnitVolume { get; set; }
        public string Durability { get; set; }
        public string FreightType { get; set; }
        public string TariffNo { get; set; }
        public decimal? DutyUnitConversion { get; set; }
        public string CountryPurchasedCode { get; set; }
        public decimal? BudgetQuantity { get; set; }
        public decimal? BudgetedAmount { get; set; }
        public decimal? BudgetProfit { get; set; }
        public byte? Blocked { get; set; }
        public byte? PriceIncludesVat { get; set; }
        public string VatbusPostingGrPrice { get; set; }
        public string GenProdPostingGroup { get; set; }
        public string PictureFileName { get; set; }
        public string CountryofOriginCode { get; set; }
        public byte? AutomaticExtTexts { get; set; }
        public string NoSeries { get; set; }
        public string TaxGroupCode { get; set; }
        public string VatprodPostingGroup { get; set; }
        public int? Reserve { get; set; }
        public string GlobalDimension1Code { get; set; }
        public string GlobalDimension2Code { get; set; }
        public int? LowLevelCode { get; set; }
        public decimal? LotSize { get; set; }
        public string SerialNos { get; set; }
        public DateTime? LastUnitCostCalcDate { get; set; }
        public decimal? RolledupMaterialCost { get; set; }
        public decimal? RolledupCapacityCost { get; set; }
        public decimal? ScrapPercent { get; set; }
        public byte? InventoryValueZero { get; set; }
        public int? DiscreteOrderQuantity { get; set; }
        public decimal? MinimumOrderQuantity { get; set; }
        public decimal? MaximumOrderQuantity { get; set; }
        public decimal? SafetyStockQuantity { get; set; }
        public decimal? OrderMultiple { get; set; }
        public string SafetyLeadTime { get; set; }
        public int? FlushingMethod { get; set; }
        public int? ReplenishmentSystem { get; set; }
        public decimal? RoundingPrecision { get; set; }
        public string SalesUnitofMeasure { get; set; }
        public string PurchUnitofMeasure { get; set; }
        public string ReorderCycle { get; set; }
        public int? ReorderingPolicy { get; set; }
        public byte? IncludeInventory { get; set; }
        public int? ManufacturingPolicy { get; set; }
        public string ManufacturerCode { get; set; }
        public string ItemCategoryCode { get; set; }
        public byte? CreatedFromNonstockItem { get; set; }
        public string ProductGroupCode { get; set; }
        public string ServiceItemGroup { get; set; }
        public string ItemTrackingCode { get; set; }
        public string LotNos { get; set; }
        public string ExpirationCalculation { get; set; }
        public string SpecialEquipmentCode { get; set; }
        public string PutawayTemplateCode { get; set; }
        public string PutawayUnitofMeasureCode { get; set; }
        public string PhysInvtCountingPeriodCode { get; set; }
        public DateTime? LastCountingPeriodUpdate { get; set; }
        public string NextCountingPeriod { get; set; }
        public byte? UseCrossDocking { get; set; }
        public string DivisionCode { get; set; }
        public DateTime? ModifyingDateofStatus { get; set; }
        public string ItemErrorCheckCode { get; set; }
        public int? ItemErrorCheckStatus { get; set; }
        public decimal? SuggestedQtyonPos { get; set; }
        public decimal? ItemCapacityValue { get; set; }
        public byte? QtynotinDecimal { get; set; }
        public byte? WeightItem { get; set; }
        public byte? WarrantyCard { get; set; }
        public string DescriptiononPos { get; set; }
        public int? DefOrderedby { get; set; }
        public int? DefOrderingMethod { get; set; }
        public string OriginalVendorNo { get; set; }
        public string OriginalVendorItemNo { get; set; }
        public byte? NoStaffDiscountAllowed { get; set; }
        public byte? NoCustomerDiscountAllowed { get; set; }
        public byte? NoItemReturnAllowed { get; set; }
        public int? Bommethod { get; set; }
        public int? BomreceiptPrint { get; set; }
        public string RecipeVersionCode { get; set; }
        public int? RecipeItemType { get; set; }
        public int? BomcostPriceDistribution { get; set; }
        public int? Bomtype { get; set; }
        public int? BomreceivingExplode { get; set; }
        public decimal? Depth { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public string VariantFrameworkCode { get; set; }
        public string SeasonCode { get; set; }
        public string LifecycleLength { get; set; }
        public DateTime? LifecycleStartingDate { get; set; }
        public DateTime? LifecycleEndingDate { get; set; }
        public byte? ErrorCheckInternalUsage { get; set; }
        public string Attrib1Code { get; set; }
        public string Attrib2Code { get; set; }
        public string Attrib3Code { get; set; }
        public string Attrib4Code { get; set; }
        public string Attrib5Code { get; set; }
        public int? Abcsales { get; set; }
        public int? Abcprofit { get; set; }
        public decimal? WastagePercent { get; set; }
        public byte? ExcludedfromPortionWeight { get; set; }
        public byte? UnaffbyMultiplFactor { get; set; }
        public byte? ExcludefromMenuRequisition { get; set; }
        public int? RecipeNoofPortions { get; set; }
        public int? MaxModifiersNoPrice { get; set; }
        public int? MaxIngrRemovedNoPrice { get; set; }
        public int? MaxIngrModifiers { get; set; }
        public decimal? ProductionTimeMin { get; set; }
        public byte? DisplayIngredientsinMonitor { get; set; }
        public byte? DisplayInstructinMonitor { get; set; }
        public string RecipeMainIngredient { get; set; }
        public string RecipeStyle { get; set; }
        public string RecipeCategory { get; set; }
        public byte? AvailableasDish { get; set; }
        public byte? UompopuponPos { get; set; }
        public int? ReplenishmentCalculationType { get; set; }
        public decimal? ManualEstimatedDailySale { get; set; }
        public decimal? StoreStockCoverReqdDays { get; set; }
        public decimal? WarehStockCoverReqdDays { get; set; }
        public string ReplenishmentSalesProfile { get; set; }
        public string ReplenishmentGradeCode { get; set; }
        public byte? NotActiveforReplenishment { get; set; }
        public byte? ExcludefromAutomReplenishm { get; set; }
        public decimal? TransferMultiple { get; set; }
        public byte? RangeinLocation { get; set; }
        public string StoreForwardSalesProfile { get; set; }
        public string WarehForwardSalesProfile { get; set; }
        public int? PurchOrderDelivery { get; set; }
        public string ReplenishasItemNo { get; set; }
        public decimal? ProfitGoalPercent { get; set; }
        public string ReplenDataProfile { get; set; }
        public int? LikeforLikeReplenMethod { get; set; }
        public int? LikeforLikeProcessMethod { get; set; }
        public int? ReplenishasItemNoMethod { get; set; }
        public string ReplenDistributionRuleCode { get; set; }
        public byte? SelectLowestPriceVendor { get; set; }
        public int? EffectiveInvSalesOrder { get; set; }
        public int? EffectiveInvPurchaseOrd { get; set; }
        public int? EffectiveInvTransferInb { get; set; }
        public int? EffectiveInvTransferOutb { get; set; }
        public byte? FuelItem { get; set; }
        public string RoutingNo { get; set; }
        public string ProductionBomno { get; set; }
        public decimal? SingleLevelMaterialCost { get; set; }
        public decimal? SingleLevelCapacityCost { get; set; }
        public decimal? SingleLevelSubcontrdCost { get; set; }
        public decimal? SingleLevelCapOvhdCost { get; set; }
        public decimal? SingleLevelMfgOvhdCost { get; set; }
        public decimal? OverheadRate { get; set; }
        public decimal? RolledupSubcontractedCost { get; set; }
        public decimal? RolledupMfgOvhdCost { get; set; }
        public decimal? RolledupCapOverheadCost { get; set; }
        public int? OrderTrackingPolicy { get; set; }
        public byte? Critical { get; set; }
        public string ItemFamilyCode { get; set; }
        public decimal? UnitPriceIncludingVat { get; set; }
        public int? PoscostCalculation { get; set; }
        public byte? NoStockPosting { get; set; }
        public byte? ZeroPriceValid { get; set; }
        public byte? QtyBecomesNegative { get; set; }
        public byte? NoDiscountAllowed { get; set; }
        public int? KeyinginPrice { get; set; }
        public byte? ScaleItem { get; set; }
        public int? KeyinginQuantity { get; set; }
        public byte? SkipCompressionWhenScanned { get; set; }
        public byte? SkipCompressionWhenPrinted { get; set; }
        public string BarcodeMask { get; set; }
        public byte? UseEanstandardBarc { get; set; }
        public decimal? QtyperBaseCompUnit { get; set; }
        public string BaseCompUnitCode { get; set; }
        public string ComparisonUnitCode { get; set; }
        public decimal? CompPriceInclVat { get; set; }
        public byte? ExplodeBominStatemPosting { get; set; }
        public byte? DisableDispensePrinting { get; set; }
        public string DispensePrinterGroup { get; set; }
        public byte? PrintVariantsShelfLabels { get; set; }
        public string CommonItemNo { get; set; }
        public string WarrantyPeriod { get; set; }
        public string DimensionValue01Code { get; set; }
        public string DimensionValue02Code { get; set; }
        public string DimensionValue03Code { get; set; }
        public string DimensionValue04Code { get; set; }
        public byte? ForSale { get; set; }
        public byte? ForPurchase { get; set; }
        public byte? ForInventory { get; set; }
        public decimal? LiterQty { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
        public string DimensionValue05Code { get; set; }
        public string DimensionValue06Code { get; set; }
        public string DimensionValue07Code { get; set; }
        public string DimensionValue08Code { get; set; }
        public string DimensionValue09Code { get; set; }
        public string DimensionValue10Code { get; set; }
        public string CukaiCode { get; set; }
    }
}
