using System;
using System.Collections.Generic;

namespace WebApplication1.Models.BalimoonBML
{
    public partial class ItemJournalLine
    {
        public int ItemJournalLineId { get; set; }
        public int ItemJournalHeaderId { get; set; }
        public string JournalTemplateName { get; set; }
        public string JournalBatchName { get; set; }
        public string DocumentNo { get; set; }
        public int SeqLineNo { get; set; }
        public string ItemNo { get; set; }
        public DateTime? PostingDate { get; set; }
        public int? EntryType { get; set; }
        public string SourceNo { get; set; }
        public string Description { get; set; }
        public string LocationCode { get; set; }
        public string InventoryPostingGroup { get; set; }
        public string SourcePostingGroup { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? InvoicedQuantity { get; set; }
        public decimal? UnitAmount { get; set; }
        public decimal? UnitCost { get; set; }
        public decimal? Amount { get; set; }
        public decimal? DiscountAmount { get; set; }
        public string SalespersPurchCode { get; set; }
        public string SourceCode { get; set; }
        public int? AppliestoEntry { get; set; }
        public int? ItemShptEntryNo { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public decimal? IndirectCostPercent { get; set; }
        public int? SourceType { get; set; }
        public string ReasonCode { get; set; }
        public int? RecurringMethod { get; set; }
        public DateTime? ExpirationDate { get; set; }
        public string RecurringFrequency { get; set; }
        public byte? DropShipment { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string CountryRegionCode { get; set; }
        public string NewLocationCode { get; set; }
        public string NewShortcutDimension1Code { get; set; }
        public string NewShortcutDimension2Code { get; set; }
        public decimal? QtyCalculated { get; set; }
        public decimal? QtyPhysInventory { get; set; }
        public int? LastItemLedgerEntryNo { get; set; }
        public byte? PhysInventory { get; set; }
        public string GenBusPostingGroup { get; set; }
        public string GenProdPostingGroup { get; set; }
        public string EntryExitPoint { get; set; }
        public DateTime? DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string PostingNoSeries { get; set; }
        public decimal? UnitCostAcy { get; set; }
        public string SourceCurrencyCode { get; set; }
        public int? DocumentType { get; set; }
        public int? DocumentSeqLineNo { get; set; }
        public string JobNo { get; set; }
        public string JobTaskNo { get; set; }
        public byte? JobPurchase { get; set; }
        public string ProdOrderNo { get; set; }
        public string VariantCode { get; set; }
        public string BinCode { get; set; }
        public decimal? QtyperUnitofMeasure { get; set; }
        public string NewBinCode { get; set; }
        public string UnitofMeasureCode { get; set; }
        public byte? DerivedfromBlanketOrder { get; set; }
        public decimal? QuantityBase { get; set; }
        public decimal? InvoicedQtyBase { get; set; }
        public int? LevelNo { get; set; }
        public int? FlushingMethod { get; set; }
        public byte? ChangedbyUser { get; set; }
        public string CrossReferenceNo { get; set; }
        public string OriginallyOrderedNo { get; set; }
        public string OriginallyOrderedVarCode { get; set; }
        public byte? OutofStockSubstitution { get; set; }
        public string ItemCategoryCode { get; set; }
        public byte? Nonstock { get; set; }
        public string PurchasingCode { get; set; }
        public string ProductGroupCode { get; set; }
        public string TransferOrderNo { get; set; }
        public DateTime? PlannedDeliveryDate { get; set; }
        public DateTime? OrderDate { get; set; }
        public int? ValueEntryType { get; set; }
        public string ItemChargeNo { get; set; }
        public decimal? InventoryValueCalculated { get; set; }
        public decimal? InventoryValueRevalued { get; set; }
        public int? VarianceType { get; set; }
        public int? InventoryValuePer { get; set; }
        public byte? PartialRevaluation { get; set; }
        public int? AppliesfromEntry { get; set; }
        public string InvoiceNo { get; set; }
        public decimal? UnitCostCalculated { get; set; }
        public decimal? UnitCostRevalued { get; set; }
        public decimal? AppliedAmount { get; set; }
        public byte? UpdateStandardCost { get; set; }
        public decimal? AmountAcy { get; set; }
        public byte? Correction { get; set; }
        public byte? Adjustment { get; set; }
        public int? AppliestoValueEntry { get; set; }
        public string InvoicetoSourceNo { get; set; }
        public int? Type { get; set; }
        public string No { get; set; }
        public string OperationNo { get; set; }
        public string WorkCenterNo { get; set; }
        public decimal? SetupTime { get; set; }
        public decimal? RunTime { get; set; }
        public decimal? StopTime { get; set; }
        public decimal? OutputQuantity { get; set; }
        public decimal? ScrapQuantity { get; set; }
        public decimal? ConcurrentCapacity { get; set; }
        public decimal? SetupTimeBase { get; set; }
        public decimal? RunTimeBase { get; set; }
        public decimal? StopTimeBase { get; set; }
        public decimal? OutputQuantityBase { get; set; }
        public decimal? ScrapQuantityBase { get; set; }
        public string CapUnitofMeasureCode { get; set; }
        public decimal? QtyperCapUnitofMeasure { get; set; }
        public DateTime? StartingTime { get; set; }
        public DateTime? EndingTime { get; set; }
        public int? ProdOrderSeqLineNo { get; set; }
        public string RoutingNo { get; set; }
        public int? RoutingReferenceNo { get; set; }
        public int? ProdOrderCompSeqLineNo { get; set; }
        public byte? Finished { get; set; }
        public int? UnitCostCalculation { get; set; }
        public byte? Subcontracting { get; set; }
        public string StopCode { get; set; }
        public string ScrapCode { get; set; }
        public string WorkCenterGroupCode { get; set; }
        public string WorkShiftCode { get; set; }
        public string ServiceOrderNo { get; set; }
        public string SerialNo { get; set; }
        public string LotNo { get; set; }
        public DateTime? WarrantyDate { get; set; }
        public string NewSerialNo { get; set; }
        public string NewLotNo { get; set; }
        public DateTime? NewItemExpirationDate { get; set; }
        public DateTime? ItemExpirationDate { get; set; }
        public string ReturnReasonCode { get; set; }
        public string PhysInvtCountingPeriodCode { get; set; }
        public int? PhysInvtCountingPeriodType { get; set; }
        public string OfferNo { get; set; }
        public string BatchNo { get; set; }
        public string Barcode { get; set; }
        public string ShipmentMethodCode { get; set; }
        public byte? OnlyTwoDimensions { get; set; }
        public string InvAdjustGroup { get; set; }
        public int? IctsourceDocType { get; set; }
        public string IctsourceDocNo { get; set; }
        public int? IctsourceSeqLineNo { get; set; }
        public string Division { get; set; }
        public string VendorNo { get; set; }
        public string PromotionNo { get; set; }
        public int? MultistoreTransaction { get; set; }
        public int? InventoryMaskCode { get; set; }
        public string AreaCode { get; set; }
        public int? ScanSeqNr { get; set; }
        public int? CreateSource { get; set; }
        public int? ModifySource { get; set; }
        public int? TempSource { get; set; }
        public string TempUserId { get; set; }
        public byte? InStoreCreatedEntry { get; set; }
        public int? StandaloneStoreAction { get; set; }
        public decimal? OverheadRate { get; set; }
        public decimal? SingleLevelMaterialCost { get; set; }
        public decimal? SingleLevelCapacityCost { get; set; }
        public decimal? SingleLevelSubcontrdCost { get; set; }
        public decimal? SingleLevelCapOvhdCost { get; set; }
        public decimal? SingleLevelMfgOvhdCost { get; set; }
        public decimal? RolledupMaterialCost { get; set; }
        public decimal? RolledupCapacityCost { get; set; }
        public decimal? RolledupSubcontractedCost { get; set; }
        public decimal? RolledupMfgOvhdCost { get; set; }
        public decimal? RolledupCapOverheadCost { get; set; }
        public string BodocNo { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
    }
}
